#!/bin/bash
sed s/INCORRECT_PASSWORD/ACCESS_DENIED/ LogA.txt > access_denied.txt
awk '{pring $4, $6}' access_denied.txt > filtered_logs.txt

cat $1_Dealer_schedule | awk -F" " '{print $1, $2, $5, $6}' | grep "$2"
